name: app_exceptions
description: A dart library with common exceptions found in a frontend application
version: 0.0.1
homepage: https://github.com/cedvdb/flutter_app_exceptions

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: any
